### ISSUE TITLE
How to move session_with_store

### ISSUE THREAD

**Issue by ghost** [ajpauwels/warp-sessions#3]
Hi, I am using this library with `async-graphql` and I would like to access `session_with_store` inside my handler.

So I have a code looks like this

```rust
.and_then(
            move |session_with_store: SessionWithStore<MemoryStore>,
                  (schema, mut request): (SchemaRoot, async_graphql::Request)| async move {
                request = request.data(session_with_store);
                
                let response = Response::from(schema.execute(request).await).into_response();
                
                Ok::<_, Infallible>((response, session_with_store))
            },
        )
        .untuple_one()
        .and_then(warp_sessions::reply::with_session);
```

The issue is that I cannot move `session_with_store` into `request.data` as it looks like that it is being use later in `warp_sessions::reply::with_session`.

I wonder if there is a way or best practice to achieve this? Thanks,

**Comment by ghost** [comment]
Might be related to https://github.com/http-rs/async-session/issues/20

**Comment by ghost** [comment]
It would be nice to make `session` inside `SessionWithStore` `Arc<Mutex>` or something, it is very common that we need to pass session around to mutate it.

**Comment by ajp-lqx** [comment]
@phungtranminh I think the solution here is to defer to the consuming code how it would like to pass around a shared, potentially mutable reference to the session, as enforcing this within `SessionWithStore` itself would restrict said code. Here is a potential solution for you to extract the session, wrap it an `Arc<RwLock>` for shared mutability, and then re-inserting it into `SessionWithStore` for processing by `with_session`:

```
                        let shared_session = Arc::new(RwLock::new(session_with_store.session));
                        shared_session
                            .write()
                            .unwrap()
                            .insert("test", "test")
                            .unwrap();
                        session_with_store.session = Arc::try_unwrap(shared_session)
                            .unwrap()
                            .into_inner()
                            .unwrap();
```

**Comment by ajpauwels** [comment]
@phungtranminh I think the solution here is to defer to the consuming code how it would like to pass around a shared, potentially mutable reference to the session, as enforcing this within `SessionWithStore` itself would restrict said code. Here is a potential solution for you to extract the session, wrap it an `Arc<RwLock>` for shared mutability, and then re-insert it into `SessionWithStore` for processing by `with_session`:

```
let shared_session = Arc::new(RwLock::new(session_with_store.session));
shared_session
    .write()
    .unwrap()
    .insert("key", "value")
    .unwrap();
session_with_store.session = Arc::try_unwrap(shared_session)
    .unwrap()
    .into_inner()
    .unwrap();
```

I will add this to the documentation.

**Comment by ajpauwels** [comment]
@phungtranminh If you check the `examples/` folder you'll find a new example under `shared_mutable_session.rs` :)

**Comment by ghost** [comment]
Thanks for the suggestion @ajpauwels it works well.

Just to be clear, I can `clone` `shared_session` with relatively cheaper cost?.

**Comment by ajpauwels** [comment]
Yes, cloning `shared_session` in this case is cheap as it simply clones a reference to the session struct and increases Arc's internal ref counter.

If this solution works for you I will go ahead and close this issue. If I missed something for any reason, please feel free to re-open or create a new issue :)

**Comment by ghost** [comment]
Thanks again @ajpauwels
